---
- name: Set locale to de_DE
  hosts: all
  tasks:
  - name: Ensure the locale exists
    locale_gen:
      name: de_DE.UTF-8
      state: present
  - name: set as default locale
    command: localectl set-locale LANG=de_DE.UTF-8
